name: Generate Snake

on:
  # run automatically every 6 hours
  schedule:
    - cron: "0 */6 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - main
    
  

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false
          ref: main
      - name: Generate Images
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg
          gif_out_path: dist/github-contribution-grid-snake.gif
      - name: Push Snake to https://github.com/YieldingExploiter/snk-img/
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: main
          build_dir: dist
          repo: YieldingExploiter/snk-img
          committer: 'YieldingBot[BOT] <94558721+YieldingBot@users.noreply.github.com>'
          author: 'YieldingBot[BOT] <94558721+YieldingBot@users.noreply.github.com>'
        env:
          GH_PAT: ${{ secrets.PAT_TOKEN }}
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
